const stbMojieDatabase = [
    { id: 'shiver1', text: `しば`, density: 0.005, friction: 1.0, restitution: 0.0 },
    { id: 'shiver2', text: `し\nば`, density: 0.005, friction: 1.0, restitution: 0.0 },
    { id: 'matari', text: `ヽ(´ー｀)ノ`, density: 0.0011, friction: 1.0, restitution: 0.01 },
    { id: 'matari1', text: `ヽ(´ー｀)ノ\n   (    )\n   ノ  ヽ`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'matari2', text: `(´ー｀)>\n(ヽ  )\nﾉ <`, density: 0.001, friction: 0.8, restitution: 0.01 },
    { id: 'matari3', text: `ヽ(´ー｀)ノ\n   (    )\n   ノωヽ`, density: 0.001, friction: 0.7, restitution: 0.01 },
    { id: 'matari4', text: `<(´ー\`)\n  (  ノ)\n   ＞ ヽ`, density: 0.001, friction: 0.8, restitution: 0.01 },
    { id: 'matari5', text: `   (´ー｀)\n  ( ヽ ヽ)\n／    >`, density: 0.001, friction: 0.8, restitution: 0.01 },
    { id: 'matari6', text: `┌──┐\n│´-\`│\n└──┘`, density: 0.002, friction: 0.9, restitution: 0.01 },
    { id: 'matari7', text: ` ≦♀≧\n(´ー｀)ノ\n<(|＿|)\n ノωヽ`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'matari8', text: `▽   Å   ▽\nヾ(;´Д\`)ｼ\n  (     )\n    >>))\n  ((○`, density: 0.001, friction: 0.9, restitution: 0.01 },
    { id: 'matari9', text: `(´ー｀)`, density: 0.005, friction: 1.0, restitution: 0.001 },
    { id: 'matari10', text: `(´ー｀)\n (ヽノ)\n ⊂  ⊃`, density: 0.0011, friction: 1.0, restitution: 0.001 },
    { id: 'matari11', text: `ヽ(´ー｀)ノ\n   ( η )\n   ノωヽ`, density: 0.001, friction: 0.7, restitution: 0.01 },
    { id: 'matari12', text: `(*´Д\`)(*'-')\nﾉ(    )ν(  )ヽ\n ノ  ヽ   ハ`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'matari13', text: `          ●\n  (;´Д\`)ﾉ\n  ﾉ(    )へ\n● くω`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'ase', text: `(;´Д\`)`, density: 0.0011, friction: 1.0, restitution: 0.05 },
    { id: 'ase1', text: `(;´Д\`)\n(ノ ヽ)\n /   >`, density: 0.001, friction: 0.7, restitution: 0.15 },
    { id: 'ase2', text: `        ●\n(;´Д\`)ﾉ\n (ヽ  )\n  > ●>`, density: 0.001, friction: 0.6, restitution: 0.15 },
    { id: 'ase3', text: `(´Д\`;)\n (ヽノ)\n  ヽノ`, density: 0.001, friction: 0.7, restitution: 0.15 },
    { id: 'ase4', text: `ヽ(;´Д\`)ﾉ\n    (ノ  )ノ`, density: 0.001, friction: 0.6, restitution: 0.15 },
    { id: 'ase5', text: `(;´Д\`)\n (～～)\n  >ω<`, density: 0.001, friction: 0.6, restitution: 0.15 },
    { id: 'ase6', text: `    ○\n○  │ ○\n│  │ │\n(  (;´Д\`)\n｜｜ ヽ  ヽ`, density: 0.0008, friction: 0.75, restitution: 0.15 },
    { id: 'ase7', text: `  (;´Д\`)ノ\n_(ヽ   )`, density: 0.001, friction: 0.9, restitution: 0.15 },
    { id: 'ase8', text: `(;´Д\`)\n∩∩ノ)`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'ase9', text: `(;´Д\`)\n    州\n ﾉ(｡〇｡)ヽ`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'ase10', text: `( (;´Д\`)\n」」  ヽヽ`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'ase11', text: `<(;´Д\`)>\n  (    )\n   ＞＜`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'ase12', text: `ヘ(;´Д\`)ヘ\n  (     )\n    ＞  ＼`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'hage', text: `ヽ(; \`Д´)ノ`, density: 0.002, friction: 0.9, restitution: 0.015 },
    { id: 'hage1', text: `ヽ(\`Д´)ﾉ\n   (  へ)\n   <`, density: 0.002, friction: 0.8, restitution: 0.01 },
    { id: 'hage2', text: ` ┐  ┌\n（    ）\n(;´Д\`)＿\n|`, density: 0.001, friction: 0.8, restitution: 0.01 },
    { id: 'hage3', text: `   (\`Д´)\n□（ ヽ┐U\n ◎－>┘◎`, density: 0.0015, friction: 0.9, restitution: 0.01 },
    { id: 'hage4', text: `(\`Д´)\n ヽノ)\n ⊂⊂`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'hage5', text: ` (\`Д´)\n￣(  V)\n   <  ＼`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'hage6', text: ` ＿＿＿＿\n(  ＿＿＿)\n(＿＿＿  )\n(＿＿＿＿)\nヽ(\`Д´)ノ\n   (   )\n   ノ  ヽ`, density: 0.002, friction: 1.0, restitution: 0.0 },
    { id: 'hage7', text: `ヽ(\`Д´)y-~~\n   (    )\n    <  ７`, density: 0.0015, friction: 1.0, restitution: 0.0 },
    { id: 'hage8', text: `●＝(\`Д´)\n     (   V)\n     <    ＼`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'hage9', text: ` ＿＿＿＿＿＿\n()＿ヽ(\`Д´))\n       (    )\n        <  <`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'ha', text: `(;´Д\`)(ﾟДﾟ;)`, density: 0.001, friction: 0.8, restitution: 0.01 },
    { id: 'ha1', text: `ヽ ヽ\n  (   )\n   (;ﾟДﾟ)\n    ヽ  ヽ`, density: 0.0012, friction: 0.8, restitution: 0.02 },
    { id: 'ha2', text: `┌(ﾟДﾟ;)y_~\n│く( へ)へ\n└─┬┬┘\n    ┴┴`, density: 0.002, friction: 0.9, restitution: 0.01 },
    { id: 'ha3', text: `ヽ(ﾟДﾟ;)\n   ( ノ)\n     ﾉ ヽ`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'ha4', text: `   (ﾟーﾟ )\n    ﾉ(   ヽ)\nへ／   <    ヽ\n＼>`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'gyaha', text: `(^Д^)`, density: 0.001, friction: 0.6, restitution: 0.013 },
    { id: 'gyaha1', text: `ヽ(^Д^)ノ\nへ(へ )`, density: 0.001, friction: 0.85, restitution: 0.015 },
    { id: 'gyaha2', text: `( ( ^Д^)\nハハハハ`, density: 0.001, friction: 0.85, restitution: 0.013 },
    { id: 'gyaha3', text: ` (^Д^)\n～(  )～\n  くく`, density: 0.001, friction: 0.85, restitution: 0.013 },
    { id: 'yousei1', text: `( '-')ﾉ`, density: 0.001, friction: 1.0, restitution: 0.01 },
    { id: 'yousei2', text: `  ('-')ﾉ\n <(   )\n  ││`, density: 0.002, friction: 0.9, restitution: 0.01 },
    { id: 'yousei3', text: `  ＞  ノ\n (   )\nノ( ,-,)ヽ`, density: 0.001, friction: 0.8, restitution: 0.02 },
    { id: 'yousei4', text: `    ( '-')ﾉ\n    (ヽへへ\n (ﾟДﾟ)ﾉノ\n  (  )\n  ﾉ＞`, density: 0.0017, friction: 0.8, restitution: 0.01 },
    { id: 'yousei5', text: `  ＿＿\n_|＿＿|_\n ( '-')>\nﾉ(   )\n ﾉ ＞`, density: 0.001, friction: 0.25, restitution: 0.01 },
    { id: 'yousei6', text: `  ＿＿\n（ ( ))\n  ||||  4\n ( '-')ノ\n<( : )\n ﾉ  ヽ`, density: 0.002, friction: 1.0, restitution: 0.01 },
    { id: 'yousei7', text: `∥( '-')y-~~\n∥<(   )＿\n|￣￣∥ヽ>\n|＿＿∥＿∥`, density: 0.001, friction: 0.99, restitution: 0.001 },
    { id: 'yousei8', text: `  |≡|\n ／  ＼\n|(;'-')|\n|(ヽ∧ﾍ|`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'yousei9', text: ` ／   ＿_\n/ ＼ /＿+ヽ\n    ヽ;'-')\n     (   )\n       >  >`, density: 0.002, friction: 0.95, restitution: 0.01 },
    { id: 'yousei10', text: `＜(#'-')y-~~\n  ＼(  )へ\n    Ｔ＼`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'yousei11', text: `＿_( '-')\n|||)ﾉノ )\n|l/< <□`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'po1', text: `('ｰ'*)\nV( )7\n < <`, density: 0.001, friction: 0.95, restitution: 0.01 },
    { id: 'car1', text: `(Д\`; )   ＿＿＿\n (┌ノ)─|ｾﾝﾁｭﾘｰ|\n  <  ヽ   ￣◎￣`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'car2', text: ` ＿＿＿  (Д\`; )\n ＼ｼｰﾏ／─(ノ- )\n   ◎      <  ヽ`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'car3', text: `  ┌-┬┐\n  ('-' ├────┐\n ├─┘│  ｾﾙｼｵ  │\n └◎─┴─◎──┷`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'car4', text: `  (´ｰ\`)\n Uгイ )□─|￣BMW￣|\n◎└く-◎    ￣◎￣`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'car5', text: ` ┌-┬┐      [やるき]\n (^Д^│(´ー\`)ﾉ\n├─┘├────┐\n└◎─┴─◎──┷`, density: 0.001, friction: 0.8, restitution: 0.015 },
    { id: 'hentai1', text: ` (´ー\`)(\`   )\n(ヽ  ( '-(ﾉ   )\n  >_( _ )ヽ< <`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'hentai2', text: ` ヽ(ﾟДﾟ)ノ\nへ(  Φ  )へ`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'nurugunyo', text: `　 ┐　>\n┌(\`Д´)┘\n　 < ω└`, density: 0.0012, friction: 0.5, restitution: 0.01 },
    { id: 'puruamakuungyo', text: `　　　　η～η～η\n     ⊂　　　　´Д\`)\n　　　　ν～ν～ν`, density: 0.0017, friction: 0.6, restitution: 0.015 },
    { id: 'iddange', text: `(´ー｀)\nヽ｜｜ノ\nノ｜｜ヽ\nヽ｜｜ノ\nノ｜｜ヽ\nヽ｜｜ノ\nノ｜｜ヽ`, density: 0.0025, friction: 0.9, restitution: 0.0 },
    { id: 'iddanga', text: `ヽ｜｜ノ\nノ｜｜ヽ\nヽ｜｜ノ\nノ｜｜ヽ\nヽ｜｜ノ\nノ｜｜ヽ\n(´ー｀)`, density: 0.0025, friction: 0.9, restitution: 0.0 },
    { id: 'nyurun', text: `  ～～～～～～\n∈＝＝＝＝;´Д\`)\n  ～～～～～～`, density: 0.002, friction: 0.7, restitution: 0.01 },
    { id: 'morugesoyo', text: `  ／⌒⌒ヽ\n ( ´ー｀ )\n  │ ¶ │\n  │    │\n  │    │\n(⌒ヽ  ノ⌒)`, density: 0.0025, friction: 0.9, restitution: 0.0 },
    { id: 'darukamaruka', text: `  ／⌒⌒ヽ\n (   '-' )\n  │ ¶ │\n  │    │\n  │    │\n(⌒ヽ  ノ⌒)`, density: 0.0025, friction: 0.9, restitution: 0.0 },
    { id: 'robo1', text: `     c  x\nΨ (´ー｀) Ψ\n ＼／(  )＼／\n      )(\n    ／ω＼\n   ｜    ｜\n   △    △`, density: 0.002, friction: 0.8, restitution: 0.0 },
    { id: 'robo2', text: `    c  x\nΨ(´ー｀)Ψ\n ＼／▽＼／\n     △\n   ／ω＼\n  ｜    ｜\n  △    △`, density: 0.002, friction: 0.8, restitution: 0.0 },
    // { id: 'robo3', text: `＼i≡⌒≡i／\n ][´ー｀][\n <(□≡□)>\n  |∥||∥|\n (___)(___)`, density: 0.0035, friction: 0.79, restitution: 0.0 },
    { id: 'food1', text: ` ┃めんつゆ┃\n ┗━━━━┛\n (ﾉ´ー｀)ノ\n（   へ）\n く`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'food2', text: `         ＼  ＼\n           ＼ね＼\nヽ(´ー｀ )ノ＼ぎ＼\n ヘ(     )     ＼  ＼\n        <        ＼／`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'food3', text: `  (わさび)\n(ﾉ´ー｀)ノ\n く く`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'wondows', text: `          △\n          ○\n          □\n  γ⌒ヽ  ｜\n  (´ー\`)ノ\n  ﾉ(＿＿)\n   |_∧_|\n   Ｕ Ｕ`, density: 0.0011, friction: 1.0, restitution: 0.05 },
    { id: 'pizza1', text: ` (⌒⌒⌒)\n  |    |\n  |    |\n (;´Д\`)＿\n<(    )ノ\n／    >`, density: 0.0012, friction: 0.6, restitution: 0.01 },
    { id: 'pizza2', text: `(⌒⌒⌒)\n  ＼    ＼\n    ＼    ＼\n      (;´Д\`)＿\n     <(    )ノ\n     ／    >`, density: 0.0012, friction: 1.0, restitution: 0.0 },
    { id: 'dog1', text: `     ∧∧\n~(  (;´犬)\n  UU  U U`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'dog2', text: `  ∧∧\n (;´犬) ['-']\n (    )っ[  ]\n~ヽつつ   LL`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'marimite1', text: `∧ミミ∧\n彡\`Д´ミ\n/彡 彡 ミ>\n  /  |`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'marimite2', text: `∧ミミ∧\n彡*'-'*ミ\n 彡ヽﾉミ\n   | |`, density: 0.0012, friction: 0.9, restitution: 0.05 },
    { id: 'dauso1', text: `(´Д\`)`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'dauso2', text: ` (´Д\`)\nъ(  ъ)\n  <  <`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'grave', text: `    ┏━━━┓\n    ┃  空  ┃\n    ┃  白  ┃\n    ┃  之  ┃\n    ┃  墓  ┃\n  ┏┻━━━┻┓\n┏┻━━━━━┻┓\n┃  ┏━━━┓  ┃\n┻━┻━━━┻━┻`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'teleho', text: `◎＜\nﾉ`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'fukuro1', text: `┌──┐「\n│ ´\`│ノ\n (ヽ  )\n  ＞＞`, density: 0.0013, friction: 1.0, restitution: 0.0 },
    { id: 'fukuro2', text: `  ┌──┐\nヽ│´｀│ﾉ\n   (     )\n   <    <`, density: 0.0013, friction: 1.0, restitution: 0.0 },
    { id: 'unko', text: `   λ\n (´ｰ｀)\n(       )`, density: 0.001, friction: 1.0, restitution: 0.0 },
    { id: 'hiphop', text: `      ／⌒ヽ\n     [||||||]\n     (´ー｀)\n  _＿|￣∥￣|＿_\nノヽ  ￣∥￣  / ヽ\n|  (￣￣∥￣￣)  |\n|  (￣￣∥￣￣)  |\n|  (￣￣∥￣￣)  |\n|  (￣￣∥￣￣)  |\nヽ_ﾉ￣￣"~￣￣ヽ_ﾉ\n ヽﾉ\`   ||    ヽノ\n |      │    ＿|\n |      │   |￣|\n |      │    ￣|\n ヽ～   人   ～ ﾉ\n  /⌒ヽ´ \`､ﾉ⌒ヽ`, density: 0.0009, friction: 1.0, restitution: 0.0 },
];
